server:
  servlet:
    context-path: /open-note
  port: 7777
logging:
  level:
    org.springframework.web: DEBUG
    com.github.note.*: DEBUG
  file: /data/applogs/note/note.log
mybatis:
  type-aliases-package: com.github.note.domain
  config-locations:  mybatis/mybatis-config.xml
  mapper-locations:  mybatis/mapper/*.xml
  configuration:
      call-setters-on-nulls: true
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://zhaokk-linux:3306/note?useUnicode=true&amp;characterEncoding=utf-8&useSSL=false
    username: root
    password: zhaokk